version: '3.8'

services:
  # Backend API Service
  backend:
    build:
      context: ./BE
      dockerfile: Dockerfile
    container_name: be-hospital
    env_file: ".env"
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app-network

  # React Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fe-hospital
    ports:
      - "5173:5173"
    networks:
      - app-network

  # Database Service (MySQL)
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: mysql-hospital
    env_file: ".env"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local
